# Generated by Django 5.1.5 on 2025-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
