# Generated by Django 5.1.5 on 2025-04-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0004_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="semester",
            field=models.IntegerField(),
        ),
    ]
